# Layer configuration

BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "security"
BBFILE_PATTERN_security = "^${LAYERDIR}/"
BBFILE_PRIORITY_security = 7

LAYERSERIES_COMPAT_security = "scarthgap kirkstone dunfell"

# Optional metadata for project visibility
LAYERDEPENDS_security = "core meta-oe meta-python"

# This layer provides custom kernel hardening and security-related packages.
